# Generated by Django 3.2.5 on 2021-07-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('c_calss', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_class', models.CharField(max_length=20)),
                ('s_birth', models.CharField(max_length=6)),
                ('s_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate')),
                ('s_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.student')),
            ],
        ),
    ]
