# Generated by Django 3.2.5 on 2021-07-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210707_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='c_calss',
            new_name='c_class',
        ),
    ]
