# Generated by Django 3.2.5 on 2021-07-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_c_calss_candidate_c_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='c_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='c_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_grade',
            field=models.IntegerField(),
        ),
    ]
